# Netlify configuration for the Face Recognition Photo App

[build]
  # The build command Netlify will run
  command = "npm install && npm run build"
  # The directory with compiled assets Netlify will serve
  publish = "dist"
  # Environment variables
  environment = { NODE_VERSION = "20", NPM_FLAGS = "--legacy-peer-deps" }

# Register custom build plugin
[[plugins]]
  package = "/netlify/build-plugins/ensure-vite"

# SPA redirect - serve index.html for all paths (for React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Development settings (when using netlify dev)
[dev]
  command = "npm run dev"
  port = 5173     # Default port for Vite
  targetPort = 5173
  framework = "vite"

# Production context settings
[context.production]
  command = "npm install && npm run build"
  environment = { NODE_ENV = "production" }

# Deploy Preview context settings (for PRs)
[context.deploy-preview]
  command = "npm install && npm run build"
  environment = { NODE_ENV = "production" }

# Branch Deploy context settings (for branches besides main/master)
[context.branch-deploy]
  command = "npm install && npm run build"
  environment = { NODE_ENV = "production" }

# Cache optimization
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# For font files
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle service worker if you have one
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "max-age=0, no-cache, no-store, must-revalidate" 