version: '3.8'

services:
  companion:
    build: .
    ports:
      - "3020:3020"
    environment:
      - NODE_ENV=development
      - PORT=3020
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - COMPANION_SECRET=${COMPANION_SECRET}
    volumes:
      - ./logs:/app/logs